export function renderUpdates(items,{esc,url,img},grouped=true){
 const years=[...new Set(items.map(i=>i.date.slice(0,4)))];
 const row=n=>`<li class="update-row"><div class="update-date"><time datetime="${esc(n.date)}">${esc(n.dateLabel)}</time><span>${esc(n.kind)}</span></div><article><h3><a href="${n.route?url(n.route):esc(n.href)}">${esc(n.title)}</a></h3><p>${esc(n.summary)}</p><a class="update-source" href="${n.route?url(n.route):esc(n.href)}">${esc(n.source)} <span aria-hidden="true">↗</span></a></article>${n.image?img(n.image,'','update-thumb'):'<span class="update-mark" aria-hidden="true">↗</span>'}</li>`;
 return grouped?`${years.map(y=>`<section class="update-year" id="updates-${y}" aria-labelledby="update-heading-${y}"><h2 id="update-heading-${y}">${y}</h2><ol class="updates-list">${items.filter(n=>n.date.startsWith(y)).map(row).join('')}</ol></section>`).join('')}`:`<ol class="updates-list">${items.map(row).join('')}</ol>`;
}
export function renderHomepage(h,updates,{esc,url,img}){
 const gallery=h.gallery.map((s,i)=>`<figure class="gallery-slide" role="group" aria-roledescription="slide" aria-label="${i+1} of ${h.gallery.length}: ${esc(s.title)}"><div class="gallery-photo ${esc(s.fit)}">${img(s.image,s.alt,'',i===0)}</div><figcaption><div><p class="eyebrow">Life at IDEAS · ${String(i+1).padStart(2,'0')}</p><h2>${esc(s.title)}</h2><p>${esc(s.caption)}</p></div><a href="${s.route?url(s.route):esc(s.href)}">${esc(s.label)} ↗</a></figcaption></figure>`).join('');
 return `<div class="home-page"><section class="home-intro wrap"><div><p class="eyebrow">University of Washington · IDEAS Research Lab</p><h1>${h.headline.split('\n').map(esc).join('<br>')}</h1></div><div class="home-intro-copy"><p class="lab-full-name">${esc(h.fullName)}</p><p>${esc(h.intro)}</p><div class="home-actions"><a class="button" href="${url('research')}">Explore our research ↗</a><a href="${url('our-team')}">Meet the lab →</a></div></div></section>
 <section class="gallery wrap" aria-label="Lab and project photo gallery" aria-roledescription="carousel" data-gallery><div class="gallery-track" id="gallery-track" tabindex="0" aria-label="Gallery slides">${gallery}</div><div class="gallery-controls" hidden><span data-gallery-status role="status" aria-live="polite">1 / ${h.gallery.length}</span><div><button type="button" data-gallery-prev aria-label="Previous photo" aria-controls="gallery-track">←</button><button type="button" data-gallery-play aria-pressed="false">Play slideshow</button><button type="button" data-gallery-next aria-label="Next photo" aria-controls="gallery-track">→</button></div></div><noscript><p class="gallery-help">Scroll horizontally to explore the gallery.</p></noscript></section>
 <section class="home-mission wrap"><p class="eyebrow">Engineering + policy + community</p><div class="mission-grid"><h2>Better energy systems begin with understanding people.</h2><p>${esc(h.mission)}</p></div><div class="method-grid">${h.approach.map((m,i)=>`<article><span>0${i+1}</span><h3>${esc(m.title)}</h3><p>${esc(m.text)}</p></article>`).join('')}</div></section>
 <section class="home-research"><div class="wrap"><div class="section-head"><div><p class="eyebrow">What we investigate</p><h2>Four connected perspectives.</h2></div><a href="${url('research')}">All projects ↗</a></div><div class="home-theme-grid">${h.themes.map((t,i)=>`<a class="home-theme" href="${url(t.route)}"><span class="theme-index">0${i+1} <span aria-hidden="true">↗</span></span><h3>${esc(t.title)}</h3><p>${esc(t.text)}</p></a>`).join('')}</div></div></section>
 <section class="home-news wrap"><div class="section-head"><div><p class="eyebrow">From the lab &amp; beyond</p><h2>News, ideas &amp; milestones.</h2></div><a href="${url('news')}">Full timeline ↗</a></div>${renderUpdates(updates.items.slice(0,5),{esc,url,img},false)}</section>
 <section class="home-connect"><div class="wrap"><div><p class="eyebrow">Research with communities</p><h2>Let’s shape energy futures together.</h2><p>We collaborate across disciplines and with communities, public agencies, utilities, and research partners.</p></div><a class="button" href="${url('opportunities')}">Connect with IDEAS ↗</a></div></section></div>`;
}
export function renderNews(updates,helpers){
 const {esc,url,img}=helpers;const years=[...new Set(updates.items.map(i=>i.date.slice(0,4)))];
 return `<div class="wrap news-page"><div class="page-intro"><p class="eyebrow">From the lab &amp; beyond</p><h1>News &amp; events</h1><p>Research, fieldwork, recognition, and stories featuring the IDEAS community.</p></div><nav class="news-years" aria-label="News timeline years">${years.map(y=>`<a href="#updates-${y}">${y}</a>`).join('')}${updates.profiles.length?'<a href="#member-features">Member features</a>':''}</nav>${renderUpdates(updates.items,helpers)}${updates.profiles.length?`<section id="member-features" class="member-features"><h2>Member features</h2><p>Profiles without a publication date.</p>${updates.profiles.map(p=>`<article class="profile-feature">${img(p.image,'','')}<div><p class="eyebrow">${esc(p.source)} · ${esc(p.dateLabel)}</p><h3><a href="${esc(p.href)}">${esc(p.title)} ↗</a></h3><p>${esc(p.summary)}</p></div></article>`).join('')}</section>`:''}</div>`;
}
