export function renderTeam({people,undergraduates,esc,img,url,link}) {
 const pi=people.find(p=>p.role==='Principal Investigator');
 const doctoral=people.filter(p=>p.role==='PhD Student');
 const undergraduateCard=p=>`<article class="undergrad-card"><p class="eyebrow">${p.end?'Past researcher':'Current researcher'}</p><h4>${esc(p.name)}</h4><p class="undergrad-role">${esc(p.role)}</p><p class="team-dates">${esc(p.dates)}</p>${p.project?`<div class="undergrad-project"><span>Research project</span><p>${esc(p.project)}</p>${p.route||p.href?link(p.route?url(p.route):p.href,p.linkLabel):''}</div>`:''}${p.profileUrl?`<p class="researcher-profile">${link(p.profileUrl,'Professional profile ↗')}</p>`:''}</article>`;
 return `<div class="wrap team-page"><section class="team-intro"><p class="eyebrow">People · IDEAS Research Lab</p><h1>Different perspectives.<br>Shared purpose.</h1><p>Meet the people working together to build more equitable, sustainable, and resilient energy systems.</p><nav class="team-nav" aria-label="Team sections"><a href="#leadership">Lab leadership</a><a href="#phd-students">PhD students</a><a href="#undergraduate-researchers">Undergraduate researchers</a></nav></section>
 <figure class="team-photo">${img('team-together.jpg','Six members of the IDEAS research group together outside a University of Washington building','',true)}<figcaption><strong>Our people, together.</strong><span>IDEAS Research Lab · University of Washington</span></figcaption></figure>
 <section id="leadership" class="team-section"><div class="team-heading"><p class="eyebrow">01 · Lab leadership</p><h2>Meet our principal investigator</h2></div><article class="team-leader">${img(pi.image,pi.name)}<div><p class="eyebrow">${esc(pi.role)}</p><h3>${esc(pi.name)}</h3><p>${esc(pi.bio)}</p>${link(pi.url,'Faculty profile ↗')}</div></article><div class="pi-affiliations"><h3>Affiliations &amp; leadership</h3><div class="affiliation-grid">${pi.affiliations.map(a=>`<article><div class="affiliation-logo ${esc(a.logoTheme)}">${img(a.logo,a.name+' logo')}</div><p class="eyebrow">${esc(a.role)}</p><h4>${esc(a.name)}</h4>${link(a.url,a.label)}</article>`).join('')}</div></div></section>
 <section id="phd-students" class="team-section"><div class="team-heading"><p class="eyebrow">02 · Doctoral research</p><h2>PhD students</h2><p>Explore our researchers’ interests, projects, and research journeys.</p></div><div class="doctoral-grid">${doctoral.map(p=>`<article class="doctoral-card">${img(p.image,p.name)}<div class="doctoral-body"><p class="eyebrow">${esc(p.role)}</p><h3>${esc(p.name)}</h3><p>${esc(p.bio)}</p><div class="doctoral-links"><a href="${url('our-team/'+p.slug)}">Research journey &amp; timeline ↗</a>${link(p.url,'Professional profile ↗')}</div></div></article>`).join('')}</div></section>
 <section id="undergraduate-researchers" class="team-section"><div class="team-heading"><p class="eyebrow">03 · Learning through research</p><h2>Undergraduate researchers</h2><p>Recognizing the students who contribute to our research, from academic-year projects to summer programs.</p></div><h3 class="undergrad-heading">Current researchers</h3><div class="undergrad-grid">${undergraduates.filter(p=>!p.end).map(undergraduateCard).join('')}</div><h3 class="undergrad-heading">Past researchers</h3><div class="undergrad-grid">${undergraduates.filter(p=>p.end).map(undergraduateCard).join('')}</div></section></div>`;
}
